name:        custom-resource
version:     0.0.1
github:      mbj/custom-resource
description: stratosphere compatible custom resources
license:     AllRightsReserved

dependencies:
- aeson                   == 1.4.2.0
- amazonka                == 1.6.1
- amazonka-cloudformation == 1.6.1
- amazonka-cognito-idp    == 1.6.1
- amazonka-core           == 1.6.1
- amazonka-lambda         == 1.6.1
- amazonka-s3             == 1.6.1
- attoparsec              == 0.13.2.2
- base                    == 4.12.0.0
- bytestring              == 0.10.8.2
- containers              == 0.6.0.1
- exceptions              == 0.10.2
- hal                     == 0.3.0
- http-client             == 0.5.14
- http-client-tls         == 0.3.5.3
- lambda-haskell-runtime  == 0.0.0.1
- lens                    == 4.17.1
- lifted-base             == 0.2.3.12
- resourcet               == 1.2.2
- source-constraints      == 0.0.0.1
- stratosphere            == 0.42.0
- text                    == 1.2.3.1
- text-conversions        == 0.3.0
- unliftio                == 0.2.11
- unliftio-core           == 0.1.2.0
- unordered-containers    == 0.2.10.0
- vector                  == 0.12.0.3
- mprelude                == 0.0.0.1

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -fplugin-opt=SourceConstraints:local:CustomResource
- -fplugin=SourceConstraints
- -funbox-strict-fields

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint == 2.1.11
