name:        custom-resource
version:     0.0.1
github:      mbj/custom-resource
description: stratosphere compatible custom resources
license:     AllRightsReserved

dependencies:
- aeson                   ^>= 1.4
- aeson-pretty            ^>= 0.8
- amazonka                == 1.6.1
- amazonka-cloudformation == 1.6.1
- amazonka-cognito-idp    == 1.6.1
- amazonka-core           == 1.6.1
- attoparsec              ^>= 0.13
- base                    ^>= 4.12
- bytestring              ^>= 0.10
- conduit                 ^>= 1.3
- containers              ^>= 0.6
- exceptions              ^>= 0.10
- filepath                ^>= 1.4
- hal                     ^>= 0.3
- hashable                ^>= 1.2
- http-client             ^>= 0.6
- http-client-tls         ^>= 0.3
- lens                    ^>= 4.17
- mprelude                == 0.0.0.1
- optparse-applicative    ^>= 0.14
- random                  ^>= 1.1
- resourcet               ^>= 1.2
- source-constraints      == 0.0.0.1
- stratosphere            ^>= 0.42
- tasty                   ^>= 1.2
- text                    ^>= 1.2
- text-conversions        ^>= 0.3
- time                    ^>= 1.8
- unliftio                ^>= 0.2
- unliftio-core           ^>= 0.1
- unordered-containers    ^>= 0.2
- vector                  ^>= 0.12

library:
  source-dirs: src

default-extensions:
- CPP
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StrictData

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -fplugin-opt=SourceConstraints:local:CustomResource
- -fplugin=SourceConstraints
- -funbox-strict-fields

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint ^>= 2.1
