build:
  haddock: false
extra-deps:
- stratosphere-0.38.0
- hal-0.3.0
- git: https://github.com/mbj/amazonka
  commit: 33aa6b71309793829b534fb29f6532d71c32b106
  subdirs:
   - amazonka-cloudformation
- git: https://github.com/mbj/lambda-haskell-runtime
  commit: 9b291c7ee9cfedb9a287ce9d9003d2b54da9466b
- git: https://github.com/mbj/mprelude
  commit: 5708d9ce9b417362e0c79cbd7b48d892e7f7f32a
- git: https://github.com/mbj/stack-deploy
  commit: 80d96ec1e9d4fca6f75c58f2c8d70d021890700c
- git: https://github.com/schirp-dso/source-constraints
  commit: 008e5ce4a6660e2f35924b019272803206e01cb2
local-bin-path: bin
packages:
- .
resolver: lts-13.28
